experiment_output_dir: Paper-IS26-experiments/

dataset:
    name: adresso
    original_audio_path: ADReSSo21/original_audios/diagnosis/train/audio
    challenge_audio_path: ADReSSo21/ADReSSo21-diagnosis/diagnosis/train/audio
    apply_denoise: true

############ ALIGNERS CONFIGURATION ############
aligners:  
  - name: full

######## SPLITS CONFIGURATION ############
splits:
  folds_amount: 8
  repetitions: 10
  group_column: subject
 
############# FEATURES CONFIGURATION ############
features: 
  - name: spectrogram
    params:
      n_fft: 400
      hop_length: 160
      sample_rate: 16000
      concatenate_segments: true
      segmenter:
        size: 30
        overlap: 20
 
############# MODEL CONFIGURATION ############
model:
  name: AcousticCNNClassifier
  n_jobs: 1
  group_column: subject
  shuffle: true
  wrap_last: true
  batch_size: 32
  epochs: 80
  dropout: 0.3
  projection_dim: 128
  channel_multiplier: 0.5
  early_stopping: 
    patience: 5
    metric: loss
  
  bootstrapping:
    n_bootstraps: 1000
    stratify: true