experiment_output_dir: IS26-experiments/
exclude_alignment_contains: non_speech

dataset:
    name: adresso
    original_audio_path: ADReSSo21/original_audios/diagnosis/train/audio
    challenge_audio_path: ADReSSo21/ADReSSo21-diagnosis/diagnosis/train/audio
    apply_enhance: true 

############ ALIGNERS CONFIGURATION ############
aligners:
  - name: silero
    params:
      threshold: 0.2
      sample_rate: 16000

########## SPLITS CONFIGURATION ############
splits:
  folds_amount: 8
  repetitions: 10
  group_column: subject

############ FEATURES CONFIGURATION ############
features:
  - name: wav2vec
    params:
      model: facebook/wav2vec2-base
      minFrames: 512
      concatenate_segments: false
 
############ MODEL CONFIGURATION ############
model:
  name: Wav2Vec2Classifier
  n_jobs: 2
  group_column: subject
  shuffle: true
  wrap_last: true
  batch_size: 32
  epochs: 80
  dropout: 0.3
  num_layers: 13
  projection_dim: 128
  early_stopping: 
    patience: 5
    metric: loss

  bootstrapping:
    n_bootstraps: 1000
    stratify: true
 