experiment_output_dir: Paper-IS26-experiments/

dataset:
    name: spanishad
    metadata: dataframes/metadata.csv
    manual_aligns: dataframes/aligns/manual_patient.pkl
    base_audio_path: 11025_16000/
    apply_denoise: true

############ ALIGNERS CONFIGURATION ############
aligners:
  - name: full
    
############ SPLITS CONFIGURATION ############
splits:
  folds_amount: 8
  repetitions: 10
  group_column: subject

############ FEATURES CONFIGURATION ############
features:  
  - name: mfcc
    params:
      n_mfcc: 40
      sample_rate: 16000
      melkwargs:
        n_fft: 400
        hop_length: 160
        n_mels: 80
        center: false
        power: 2.0
        mel_scale: slaney
        norm: slaney
      concatenate_segments: true
      segmenter:
        size: 30 # seconds
        overlap: 20 # seconds

############ MODEL CONFIGURATION ############
model:
  name: AcousticCNNClassifier
  n_jobs: 2
  group_column: subject
  shuffle: true
  wrap_last: true
  batch_size: 32
  epochs: 80
  dropout: 0.3
  projection_dim: 128
  early_stopping: 
    patience: 10
    metric: loss
  
  bootstrapping:
    n_bootstraps: 1000
    stratify: true