experiment_output_dir: IS26-experiments/
exclude_alignment_contains: non_speech

dataset:
    name: spanishad
    metadata: SpanishAD/dataframes/metadata.csv
    manual_aligns: SpanishAD/dataframes/aligns/manual_patient.pkl
    base_audio_path: SpanishAD/audios/
    apply_enhance: true

############ ALIGNERS CONFIGURATION ############
aligners:
  - name: manual
    params:
      filename: manual_ipu-only_patient

############ SPLITS CONFIGURATION ############
splits:
  folds_amount: 8
  repetitions: 10
  group_column: subject

############ FEATURES CONFIGURATION ############
features:    
  - name: mfcc
    params:
      n_mfcc: 40
      sample_rate: 16000
      melkwargs:
        n_fft: 400
        hop_length: 160
        n_mels: 80
        center: false
        power: 2.0
        mel_scale: slaney
        norm: slaney
      concatenate_segments: false
        
############ MODEL CONFIGURATION ############
model:
  name: AcousticCNNClassifier
  n_jobs: 2
  group_column: subject
  shuffle: true
  wrap_last: true
  batch_size: 32
  epochs: 80
  dropout: 0.3
  projection_dim: 128
  early_stopping: 
    patience: 10
    metric: loss
  
  bootstrapping:
    n_bootstraps: 1000
    stratify: true