experiment_output_dir: experiment-output/
only_alignment_contains: non_speech # For only non-speech segments. If empty, all segments will be used for features extraction and modeling.
exclude_alignment_contains: non_speech # For only speech segments. If empty, all segments will be used for features extraction and modeling.

dataset:
    name: <dataset_name>
    original_audio_path: path/to/original/audios
    challenge_audio_path: path/to/challenge/audios
    apply_denoise: true # Whether to apply speech enhancement denoising. It will be applied over the original audio files.

############ ALIGNERS CONFIGURATION ############
aligners:  
  - name: <aligner_name>
    params:
      sample_rate: 16000
      audio_path: path/to/audio/files/ [optional]
      samples_to_ignore: path/to/samples_to_ignore.csv [optional]
      # Other aligner-specific parameters
      
      clip:
        type: 'fixed'
        keep_from: 'start'
        value: 30 # seconds
      
######## SPLITS CONFIGURATION ############
splits:
  folds_amount: 8
  repetitions: 10
  group_column: subject
 
############# FEATURES CONFIGURATION ############
features: 
  - name: mfcc
    params:
      n_mfcc: 40
      sample_rate: 16000
      melkwargs:
        n_fft: 400
        hop_length: 160
        n_mels: 80
        center: false
        power: 2.0
        mel_scale: slaney
        norm: slaney
      concatenate_audio_segments: true  # This will concatenate all the segments of an audio file before extracting features. 
      concatenate_segments: false       # This will extract features for each segment and then concatenate them.
      segmenter:                      # You can optionally specify a segmenter to split the feature representation into fixed-size segments.
        size: 5
        overlap: 4
  
############# MODEL CONFIGURATION ############
model:
  name: AcousticCNNClassifier # Wav2VecClassifier
  n_jobs: 4                   # Number of parallel jobs for training. 
  group_column: subject
  shuffle: true
  wrap_last: true
  batch_size: 32
  epochs: 80
  dropout: 0.3
  projection_dim: 128
  early_stopping: 
    patience: 5
    metric: loss
  
  bootstrapping:
    n_bootstraps: 1000
    stratify: true