experiment_output_dir: experiment-output/
only_alignment_contains: ""       # For only non-speech segments. Keep empty to use all alignments.
exclude_alignment_contains: ""    # For excluding a segment type (e.g.g. speech-only). Keep empty to use all alignments.
cache: false

########## OPTIONAL DATASET CONFIGURATION ##########
dataset:
    name: <dataset_name>
    # ADReSSo reader:
      # original_audio_path: path/to/original/audios
      # challenge_audio_path: path/to/challenge/audios
    # SpanishAD reader:
      # base_audio_path: path/to/audios
      # metadata: path/to/metadata.csv
      # manual_aligns: path/to/manual_alignments.pkl
    samples_to_filter: ""
    apply_enhance: true

############ ALIGNERS CONFIGURATION ############
aligners:
  - name: <aligner_name>
    params:
      sample_rate: 16000
      # audio_path: path/to/audio/files/
      # samples_to_ignore: path/to/samples_to_ignore.csv
      clip:
        type: 'fixed'
        keep_from: 'start'
        value: 30
    
  - name: whole_audio

############ SPLITS CONFIGURATION ############
splits:
  folds_amount: 8
  repetitions: 10
  group_column: subject

############# FEATURES CONFIGURATION ############
features:
  - name: mfcc
    params:
      n_mfcc: 40
      sample_rate: 16000
      melkwargs:
        n_fft: 400
        hop_length: 160
        n_mels: 80
        center: false
        power: 2.0
        mel_scale: slaney
        norm: slaney
      concatenate_segments: false
      segmenter:
        size: 30
        overlap: 20

############# MODEL CONFIGURATION ############
model:
  name: AcousticCNNClassifier
  n_jobs: 4
  group_column: subject
  shuffle: true
  wrap_last: true
  batch_size: 32
  epochs: 80
  dropout: 0.3
  projection_dim: 128
  early_stopping:
    patience: 5
    metric: loss
  bootstrapping:
    n_bootstraps: 1000
    stratify: true
